--Queries for Trainers Table
SELECT * FROM Trainers;
DELETE FROM Trainers WHERE condition;


--Queries for Classes Table
SELECT * FROM Classes;
DELETE FROM Classes WHERE condition;


--Queries for ClassRegistrations
SELECT * FROM ClassRegistrations;
DELETE FROM ClassRegistrations;
--Queries for Equipment
SELECT * FROM Equipment; 
DELETE FROM Equipment WHERE condition;

--Queries for Members
SELECT * FROM Members;
DELETE FROM Members WHERE condition;

